// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_file_manager.proto

package fileManager.savableModels;

public final class TableProtoContainer {
  private TableProtoContainer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TableProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fileManager.savableModels.TableProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
     */
    fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto getHeader();
    /**
     * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
     */
    fileManager.savableModels.TableProtoContainer.TableProto.HeaderProtoOrBuilder getHeaderOrBuilder();

    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.RowProto> 
        getRowsList();
    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    fileManager.savableModels.TableProtoContainer.TableProto.RowProto getRows(int index);
    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    java.util.List<? extends fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder getRowsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code fileManager.savableModels.TableProto}
   */
  public static final class TableProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:fileManager.savableModels.TableProto)
      TableProtoOrBuilder {
    // Use TableProto.newBuilder() to construct.
    private TableProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TableProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TableProto defaultInstance;
    public static TableProto getDefaultInstance() {
      return defaultInstance;
    }

    public TableProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TableProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 34: {
              fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                rows_ = new java.util.ArrayList<fileManager.savableModels.TableProtoContainer.TableProto.RowProto>();
                mutable_bitField0_ |= 0x00000004;
              }
              rows_.add(input.readMessage(fileManager.savableModels.TableProtoContainer.TableProto.RowProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fileManager.savableModels.TableProtoContainer.TableProto.class, fileManager.savableModels.TableProtoContainer.TableProto.Builder.class);
    }

    public static com.google.protobuf.Parser<TableProto> PARSER =
        new com.google.protobuf.AbstractParser<TableProto>() {
      public TableProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TableProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TableProto> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code fileManager.savableModels.TableProto.Datatype}
     */
    public enum Datatype
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>VARCHAR = 0;</code>
       */
      VARCHAR(0, 0),
      /**
       * <code>INTEGER = 1;</code>
       */
      INTEGER(1, 1),
      /**
       * <code>FLOAT = 2;</code>
       */
      FLOAT(2, 2),
      /**
       * <code>DATE = 3;</code>
       */
      DATE(3, 3),
      ;

      /**
       * <code>VARCHAR = 0;</code>
       */
      public static final int VARCHAR_VALUE = 0;
      /**
       * <code>INTEGER = 1;</code>
       */
      public static final int INTEGER_VALUE = 1;
      /**
       * <code>FLOAT = 2;</code>
       */
      public static final int FLOAT_VALUE = 2;
      /**
       * <code>DATE = 3;</code>
       */
      public static final int DATE_VALUE = 3;


      public final int getNumber() { return value; }

      public static Datatype valueOf(int value) {
        switch (value) {
          case 0: return VARCHAR;
          case 1: return INTEGER;
          case 2: return FLOAT;
          case 3: return DATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Datatype>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Datatype>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Datatype>() {
              public Datatype findValueByNumber(int number) {
                return Datatype.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return fileManager.savableModels.TableProtoContainer.TableProto.getDescriptor().getEnumTypes().get(0);
      }

      private static final Datatype[] VALUES = values();

      public static Datatype valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Datatype(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:fileManager.savableModels.TableProto.Datatype)
    }

    public interface HeaderProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fileManager.savableModels.TableProto.HeaderProto)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated string cols_name = 1;</code>
       */
      com.google.protobuf.ProtocolStringList
          getColsNameList();
      /**
       * <code>repeated string cols_name = 1;</code>
       */
      int getColsNameCount();
      /**
       * <code>repeated string cols_name = 1;</code>
       */
      java.lang.String getColsName(int index);
      /**
       * <code>repeated string cols_name = 1;</code>
       */
      com.google.protobuf.ByteString
          getColsNameBytes(int index);

      /**
       * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
       */
      java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.Datatype> getColsTypeList();
      /**
       * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
       */
      int getColsTypeCount();
      /**
       * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
       */
      fileManager.savableModels.TableProtoContainer.TableProto.Datatype getColsType(int index);
    }
    /**
     * Protobuf type {@code fileManager.savableModels.TableProto.HeaderProto}
     */
    public static final class HeaderProto extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:fileManager.savableModels.TableProto.HeaderProto)
        HeaderProtoOrBuilder {
      // Use HeaderProto.newBuilder() to construct.
      private HeaderProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private HeaderProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final HeaderProto defaultInstance;
      public static HeaderProto getDefaultInstance() {
        return defaultInstance;
      }

      public HeaderProto getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private HeaderProto(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  colsName_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                colsName_.add(bs);
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                fileManager.savableModels.TableProtoContainer.TableProto.Datatype value = fileManager.savableModels.TableProtoContainer.TableProto.Datatype.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                  } else {
                  if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    colsType_ = new java.util.ArrayList<fileManager.savableModels.TableProtoContainer.TableProto.Datatype>();
                    mutable_bitField0_ |= 0x00000002;
                  }
                  colsType_.add(value);
                }
                break;
              }
              case 18: {
                int length = input.readRawVarint32();
                int oldLimit = input.pushLimit(length);
                while(input.getBytesUntilLimit() > 0) {
                  int rawValue = input.readEnum();
                  fileManager.savableModels.TableProtoContainer.TableProto.Datatype value = fileManager.savableModels.TableProtoContainer.TableProto.Datatype.valueOf(rawValue);
                  if (value == null) {
                    unknownFields.mergeVarintField(2, rawValue);
                    } else {
                    if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                      colsType_ = new java.util.ArrayList<fileManager.savableModels.TableProtoContainer.TableProto.Datatype>();
                      mutable_bitField0_ |= 0x00000002;
                    }
                    colsType_.add(value);
                  }
                }
                input.popLimit(oldLimit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            colsName_ = colsName_.getUnmodifiableView();
          }
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            colsType_ = java.util.Collections.unmodifiableList(colsType_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_HeaderProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_HeaderProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.class, fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.Builder.class);
      }

      public static com.google.protobuf.Parser<HeaderProto> PARSER =
          new com.google.protobuf.AbstractParser<HeaderProto>() {
        public HeaderProto parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeaderProto(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<HeaderProto> getParserForType() {
        return PARSER;
      }

      public static final int COLS_NAME_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList colsName_;
      /**
       * <code>repeated string cols_name = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getColsNameList() {
        return colsName_;
      }
      /**
       * <code>repeated string cols_name = 1;</code>
       */
      public int getColsNameCount() {
        return colsName_.size();
      }
      /**
       * <code>repeated string cols_name = 1;</code>
       */
      public java.lang.String getColsName(int index) {
        return colsName_.get(index);
      }
      /**
       * <code>repeated string cols_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getColsNameBytes(int index) {
        return colsName_.getByteString(index);
      }

      public static final int COLS_TYPE_FIELD_NUMBER = 2;
      private java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.Datatype> colsType_;
      /**
       * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
       */
      public java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.Datatype> getColsTypeList() {
        return colsType_;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
       */
      public int getColsTypeCount() {
        return colsType_.size();
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
       */
      public fileManager.savableModels.TableProtoContainer.TableProto.Datatype getColsType(int index) {
        return colsType_.get(index);
      }

      private void initFields() {
        colsName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        colsType_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < colsName_.size(); i++) {
          output.writeBytes(1, colsName_.getByteString(i));
        }
        for (int i = 0; i < colsType_.size(); i++) {
          output.writeEnum(2, colsType_.get(i).getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < colsName_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(colsName_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getColsNameList().size();
        }
        {
          int dataSize = 0;
          for (int i = 0; i < colsType_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeEnumSizeNoTag(colsType_.get(i).getNumber());
          }
          size += dataSize;
          size += 1 * colsType_.size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code fileManager.savableModels.TableProto.HeaderProto}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:fileManager.savableModels.TableProto.HeaderProto)
          fileManager.savableModels.TableProtoContainer.TableProto.HeaderProtoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_HeaderProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_HeaderProto_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.class, fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.Builder.class);
        }

        // Construct using fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          colsName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          colsType_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_HeaderProto_descriptor;
        }

        public fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto getDefaultInstanceForType() {
          return fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.getDefaultInstance();
        }

        public fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto build() {
          fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto buildPartial() {
          fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto result = new fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            colsName_ = colsName_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.colsName_ = colsName_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            colsType_ = java.util.Collections.unmodifiableList(colsType_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.colsType_ = colsType_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto) {
            return mergeFrom((fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto other) {
          if (other == fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.getDefaultInstance()) return this;
          if (!other.colsName_.isEmpty()) {
            if (colsName_.isEmpty()) {
              colsName_ = other.colsName_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureColsNameIsMutable();
              colsName_.addAll(other.colsName_);
            }
            onChanged();
          }
          if (!other.colsType_.isEmpty()) {
            if (colsType_.isEmpty()) {
              colsType_ = other.colsType_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureColsTypeIsMutable();
              colsType_.addAll(other.colsType_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.LazyStringList colsName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureColsNameIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            colsName_ = new com.google.protobuf.LazyStringArrayList(colsName_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated string cols_name = 1;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getColsNameList() {
          return colsName_.getUnmodifiableView();
        }
        /**
         * <code>repeated string cols_name = 1;</code>
         */
        public int getColsNameCount() {
          return colsName_.size();
        }
        /**
         * <code>repeated string cols_name = 1;</code>
         */
        public java.lang.String getColsName(int index) {
          return colsName_.get(index);
        }
        /**
         * <code>repeated string cols_name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getColsNameBytes(int index) {
          return colsName_.getByteString(index);
        }
        /**
         * <code>repeated string cols_name = 1;</code>
         */
        public Builder setColsName(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureColsNameIsMutable();
          colsName_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string cols_name = 1;</code>
         */
        public Builder addColsName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureColsNameIsMutable();
          colsName_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string cols_name = 1;</code>
         */
        public Builder addAllColsName(
            java.lang.Iterable<java.lang.String> values) {
          ensureColsNameIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, colsName_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string cols_name = 1;</code>
         */
        public Builder clearColsName() {
          colsName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string cols_name = 1;</code>
         */
        public Builder addColsNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureColsNameIsMutable();
          colsName_.add(value);
          onChanged();
          return this;
        }

        private java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.Datatype> colsType_ =
          java.util.Collections.emptyList();
        private void ensureColsTypeIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            colsType_ = new java.util.ArrayList<fileManager.savableModels.TableProtoContainer.TableProto.Datatype>(colsType_);
            bitField0_ |= 0x00000002;
          }
        }
        /**
         * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
         */
        public java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.Datatype> getColsTypeList() {
          return java.util.Collections.unmodifiableList(colsType_);
        }
        /**
         * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
         */
        public int getColsTypeCount() {
          return colsType_.size();
        }
        /**
         * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
         */
        public fileManager.savableModels.TableProtoContainer.TableProto.Datatype getColsType(int index) {
          return colsType_.get(index);
        }
        /**
         * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
         */
        public Builder setColsType(
            int index, fileManager.savableModels.TableProtoContainer.TableProto.Datatype value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColsTypeIsMutable();
          colsType_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
         */
        public Builder addColsType(fileManager.savableModels.TableProtoContainer.TableProto.Datatype value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColsTypeIsMutable();
          colsType_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
         */
        public Builder addAllColsType(
            java.lang.Iterable<? extends fileManager.savableModels.TableProtoContainer.TableProto.Datatype> values) {
          ensureColsTypeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, colsType_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated .fileManager.savableModels.TableProto.Datatype cols_type = 2;</code>
         */
        public Builder clearColsType() {
          colsType_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:fileManager.savableModels.TableProto.HeaderProto)
      }

      static {
        defaultInstance = new HeaderProto(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:fileManager.savableModels.TableProto.HeaderProto)
    }

    public interface RowProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fileManager.savableModels.TableProto.RowProto)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated string value = 1;</code>
       */
      com.google.protobuf.ProtocolStringList
          getValueList();
      /**
       * <code>repeated string value = 1;</code>
       */
      int getValueCount();
      /**
       * <code>repeated string value = 1;</code>
       */
      java.lang.String getValue(int index);
      /**
       * <code>repeated string value = 1;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes(int index);
    }
    /**
     * Protobuf type {@code fileManager.savableModels.TableProto.RowProto}
     */
    public static final class RowProto extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:fileManager.savableModels.TableProto.RowProto)
        RowProtoOrBuilder {
      // Use RowProto.newBuilder() to construct.
      private RowProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private RowProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final RowProto defaultInstance;
      public static RowProto getDefaultInstance() {
        return defaultInstance;
      }

      public RowProto getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private RowProto(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  value_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                value_.add(bs);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = value_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_RowProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_RowProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fileManager.savableModels.TableProtoContainer.TableProto.RowProto.class, fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder.class);
      }

      public static com.google.protobuf.Parser<RowProto> PARSER =
          new com.google.protobuf.AbstractParser<RowProto>() {
        public RowProto parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RowProto(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<RowProto> getParserForType() {
        return PARSER;
      }

      public static final int VALUE_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList value_;
      /**
       * <code>repeated string value = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValueList() {
        return value_;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public java.lang.String getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes(int index) {
        return value_.getByteString(index);
      }

      private void initFields() {
        value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < value_.size(); i++) {
          output.writeBytes(1, value_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < value_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(value_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getValueList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static fileManager.savableModels.TableProtoContainer.TableProto.RowProto parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(fileManager.savableModels.TableProtoContainer.TableProto.RowProto prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code fileManager.savableModels.TableProto.RowProto}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:fileManager.savableModels.TableProto.RowProto)
          fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_RowProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_RowProto_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  fileManager.savableModels.TableProtoContainer.TableProto.RowProto.class, fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder.class);
        }

        // Construct using fileManager.savableModels.TableProtoContainer.TableProto.RowProto.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_RowProto_descriptor;
        }

        public fileManager.savableModels.TableProtoContainer.TableProto.RowProto getDefaultInstanceForType() {
          return fileManager.savableModels.TableProtoContainer.TableProto.RowProto.getDefaultInstance();
        }

        public fileManager.savableModels.TableProtoContainer.TableProto.RowProto build() {
          fileManager.savableModels.TableProtoContainer.TableProto.RowProto result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public fileManager.savableModels.TableProtoContainer.TableProto.RowProto buildPartial() {
          fileManager.savableModels.TableProtoContainer.TableProto.RowProto result = new fileManager.savableModels.TableProtoContainer.TableProto.RowProto(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = value_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.value_ = value_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof fileManager.savableModels.TableProtoContainer.TableProto.RowProto) {
            return mergeFrom((fileManager.savableModels.TableProtoContainer.TableProto.RowProto)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(fileManager.savableModels.TableProtoContainer.TableProto.RowProto other) {
          if (other == fileManager.savableModels.TableProtoContainer.TableProto.RowProto.getDefaultInstance()) return this;
          if (!other.value_.isEmpty()) {
            if (value_.isEmpty()) {
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValueIsMutable();
              value_.addAll(other.value_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          fileManager.savableModels.TableProtoContainer.TableProto.RowProto parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (fileManager.savableModels.TableProtoContainer.TableProto.RowProto) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.LazyStringList value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureValueIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = new com.google.protobuf.LazyStringArrayList(value_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getValueList() {
          return value_.getUnmodifiableView();
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public int getValueCount() {
          return value_.size();
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public java.lang.String getValue(int index) {
          return value_.get(index);
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes(int index) {
          return value_.getByteString(index);
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder setValue(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder addValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder addAllValue(
            java.lang.Iterable<java.lang.String> values) {
          ensureValueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, value_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder clearValue() {
          value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string value = 1;</code>
         */
        public Builder addValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.add(value);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:fileManager.savableModels.TableProto.RowProto)
      }

      static {
        defaultInstance = new RowProto(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:fileManager.savableModels.TableProto.RowProto)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADER_FIELD_NUMBER = 4;
    private fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto header_;
    /**
     * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
     */
    public fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto getHeader() {
      return header_;
    }
    /**
     * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
     */
    public fileManager.savableModels.TableProtoContainer.TableProto.HeaderProtoOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    public static final int ROWS_FIELD_NUMBER = 5;
    private java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.RowProto> rows_;
    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    public java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.RowProto> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    public java.util.List<? extends fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    public fileManager.savableModels.TableProtoContainer.TableProto.RowProto getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
     */
    public fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    private void initFields() {
      name_ = "";
      header_ = fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.getDefaultInstance();
      rows_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(4, header_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(5, rows_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, header_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, rows_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fileManager.savableModels.TableProtoContainer.TableProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fileManager.savableModels.TableProtoContainer.TableProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fileManager.savableModels.TableProtoContainer.TableProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fileManager.savableModels.TableProtoContainer.TableProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fileManager.savableModels.TableProtoContainer.TableProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fileManager.savableModels.TableProtoContainer.TableProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fileManager.savableModels.TableProtoContainer.TableProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fileManager.savableModels.TableProtoContainer.TableProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fileManager.savableModels.TableProtoContainer.TableProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fileManager.savableModels.TableProtoContainer.TableProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fileManager.savableModels.TableProtoContainer.TableProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fileManager.savableModels.TableProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fileManager.savableModels.TableProto)
        fileManager.savableModels.TableProtoContainer.TableProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fileManager.savableModels.TableProtoContainer.TableProto.class, fileManager.savableModels.TableProtoContainer.TableProto.Builder.class);
      }

      // Construct using fileManager.savableModels.TableProtoContainer.TableProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getRowsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (headerBuilder_ == null) {
          header_ = fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fileManager.savableModels.TableProtoContainer.internal_static_fileManager_savableModels_TableProto_descriptor;
      }

      public fileManager.savableModels.TableProtoContainer.TableProto getDefaultInstanceForType() {
        return fileManager.savableModels.TableProtoContainer.TableProto.getDefaultInstance();
      }

      public fileManager.savableModels.TableProtoContainer.TableProto build() {
        fileManager.savableModels.TableProtoContainer.TableProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fileManager.savableModels.TableProtoContainer.TableProto buildPartial() {
        fileManager.savableModels.TableProtoContainer.TableProto result = new fileManager.savableModels.TableProtoContainer.TableProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fileManager.savableModels.TableProtoContainer.TableProto) {
          return mergeFrom((fileManager.savableModels.TableProtoContainer.TableProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fileManager.savableModels.TableProtoContainer.TableProto other) {
        if (other == fileManager.savableModels.TableProtoContainer.TableProto.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000004);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasHeader()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fileManager.savableModels.TableProtoContainer.TableProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fileManager.savableModels.TableProtoContainer.TableProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto header_ = fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto, fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.Builder, fileManager.savableModels.TableProtoContainer.TableProto.HeaderProtoOrBuilder> headerBuilder_;
      /**
       * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
       */
      public fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
       */
      public Builder setHeader(fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
       */
      public Builder setHeader(
          fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
       */
      public Builder mergeHeader(fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              header_ != fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.getDefaultInstance()) {
            header_ =
              fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
       */
      public fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
       */
      public fileManager.savableModels.TableProtoContainer.TableProto.HeaderProtoOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .fileManager.savableModels.TableProto.HeaderProto header = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto, fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.Builder, fileManager.savableModels.TableProtoContainer.TableProto.HeaderProtoOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto, fileManager.savableModels.TableProtoContainer.TableProto.HeaderProto.Builder, fileManager.savableModels.TableProtoContainer.TableProto.HeaderProtoOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.RowProto> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          rows_ = new java.util.ArrayList<fileManager.savableModels.TableProtoContainer.TableProto.RowProto>(rows_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          fileManager.savableModels.TableProtoContainer.TableProto.RowProto, fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder, fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.RowProto> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public fileManager.savableModels.TableProtoContainer.TableProto.RowProto getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public Builder setRows(
          int index, fileManager.savableModels.TableProtoContainer.TableProto.RowProto value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public Builder setRows(
          int index, fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public Builder addRows(fileManager.savableModels.TableProtoContainer.TableProto.RowProto value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public Builder addRows(
          int index, fileManager.savableModels.TableProtoContainer.TableProto.RowProto value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public Builder addRows(
          fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public Builder addRows(
          int index, fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends fileManager.savableModels.TableProtoContainer.TableProto.RowProto> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public java.util.List<? extends fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            fileManager.savableModels.TableProtoContainer.TableProto.RowProto.getDefaultInstance());
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, fileManager.savableModels.TableProtoContainer.TableProto.RowProto.getDefaultInstance());
      }
      /**
       * <code>repeated .fileManager.savableModels.TableProto.RowProto rows = 5;</code>
       */
      public java.util.List<fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fileManager.savableModels.TableProtoContainer.TableProto.RowProto, fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder, fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fileManager.savableModels.TableProtoContainer.TableProto.RowProto, fileManager.savableModels.TableProtoContainer.TableProto.RowProto.Builder, fileManager.savableModels.TableProtoContainer.TableProto.RowProtoOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:fileManager.savableModels.TableProto)
    }

    static {
      defaultInstance = new TableProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fileManager.savableModels.TableProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fileManager_savableModels_TableProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fileManager_savableModels_TableProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fileManager_savableModels_TableProto_HeaderProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fileManager_savableModels_TableProto_HeaderProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fileManager_savableModels_TableProto_RowProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fileManager_savableModels_TableProto_RowProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto_file_manager.proto\022\031fileManager." +
      "savableModels\"\326\002\n\nTableProto\022\014\n\004name\030\001 \002" +
      "(\t\022A\n\006header\030\004 \002(\01321.fileManager.savable" +
      "Models.TableProto.HeaderProto\022<\n\004rows\030\005 " +
      "\003(\0132..fileManager.savableModels.TablePro" +
      "to.RowProto\032c\n\013HeaderProto\022\021\n\tcols_name\030" +
      "\001 \003(\t\022A\n\tcols_type\030\002 \003(\0162..fileManager.s" +
      "avableModels.TableProto.Datatype\032\031\n\010RowP" +
      "roto\022\r\n\005value\030\001 \003(\t\"9\n\010Datatype\022\013\n\007VARCH" +
      "AR\020\000\022\013\n\007INTEGER\020\001\022\t\n\005FLOAT\020\002\022\010\n\004DATE\020\003B0",
      "\n\031fileManager.savableModelsB\023TableProtoC" +
      "ontainer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_fileManager_savableModels_TableProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fileManager_savableModels_TableProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fileManager_savableModels_TableProto_descriptor,
        new java.lang.String[] { "Name", "Header", "Rows", });
    internal_static_fileManager_savableModels_TableProto_HeaderProto_descriptor =
      internal_static_fileManager_savableModels_TableProto_descriptor.getNestedTypes().get(0);
    internal_static_fileManager_savableModels_TableProto_HeaderProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fileManager_savableModels_TableProto_HeaderProto_descriptor,
        new java.lang.String[] { "ColsName", "ColsType", });
    internal_static_fileManager_savableModels_TableProto_RowProto_descriptor =
      internal_static_fileManager_savableModels_TableProto_descriptor.getNestedTypes().get(1);
    internal_static_fileManager_savableModels_TableProto_RowProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fileManager_savableModels_TableProto_RowProto_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
